### ISSUE TITLE
Provide a default tsconfig object as default value

### ISSUE THREAD

**Issue by BioPhoton** [timdeschryver/find-deprecations#8]
I suggest in cases where the user is not aware of where the right tsconfig.json is located or just hits enter we can provide a default value/object there points to the root and all files would get crawled.

I would create a const here:
https://github.com/timdeschryver/find-deprecations/blob/master/lib/config.ts#L10

and adopt the logic here: 
https://github.com/timdeschryver/find-deprecations/blob/master/lib/crawler.ts#L20

**Comment by timdeschryver** [comment]
This is how I've done it previously (in non TS projects).
ts-morph also allows us to add files, instead of pointing to a tsconfig file.

Implementation can be found in [tl-user-event-mod](https://github.com/timdeschryver/tl-user-event-mod/blob/master/src/index.ts#L6-L14).

If you want, you can take this task 🙂
